import os
import sys
import subprocess
import platform
import getpass

class VDGS:
    def __init__(self, base_dir_name="virtual_root"):
        # The authentic root directory managed and generated by VDGS
        self.host_root_path = os.path.abspath(base_dir_name)
        self.host_current_path = self.host_root_path
        self.is_running = True
        self.os_type = platform.system()
        
        # Administrator password for external authentication
        self.admin_password = "vdgs_secure_pass"

        # Hardware and Network Isolation state management (Default: Isolated/Disabled)
        self.is_network_enabled = False
        self.connected_usb_device = None
        self.usb_mount_point = os.path.join(self.host_root_path, "mnt", "usb")

        # Automatic generation of essential directories
        if not os.path.exists(self.host_root_path):
            os.makedirs(self.host_root_path)
        if not os.path.exists(self.usb_mount_point):
            os.makedirs(self.usb_mount_point)

    def unix_to_windows_path(self, path_str):
        return path_str.replace("/", os.sep)

    def is_safe_path(self, check_path):
        """Strict validator to deny any access outside the VDGS managed boundary."""
        try:
            abs_path = os.path.abspath(check_path)
            return os.path.commonpath([self.host_root_path, abs_path]) == self.host_root_path
        except Exception:
            return False

    def get_virtual_prompt_path(self):
        if self.host_current_path == self.host_root_path:
            return "/"
        rel = os.path.relpath(self.host_current_path, self.host_root_path)
        return "/" + rel.replace(os.sep, "/")

    def pre_check_security(self, command_line):
        """String-level check to block malicious directory traversal attacks."""
        forbidden_keywords = ["/..", "../", "..\\", ".. "]
        for kw in forbidden_keywords:
            if kw in command_line:
                return False
        return True

    def authenticate_external(self):
        """Simulates external administrative approval using a password gate."""
        print("\n[VDGS Auth] ⚠️ External hardware/network request detected.")
        print("[VDGS Auth] Administrative approval required from the host system.")
        entered = getpass.getpass("Enter Admin Password: ")
        if entered == self.admin_password:
            print("[VDGS Auth] 🔓 Authentication successful. Access granted.\n")
            return True
        else:
            print("[VDGS Auth] ❌ Authentication failed. Access denied.\n")
            return False

    def handle_vdgs_commands(self, tokens):
        """Handles VDGS core administrative extension commands."""
        if not tokens:
            return False
            
        cmd = tokens[0]

        # --- USB Virtual Mapping Commands ---
        if cmd == "vdgs-usb":
            if len(tokens) > 1 and tokens[1] == "--connect":
                if len(tokens) < 4:
                    print("Usage: vdgs-usb --connect [DeviceName] [HostPathOrPort]")
                    return True
                if self.connected_usb_device:
                    print(f"VDGS [USB]: Device '{self.connected_usb_device}' is already connected.")
                    return True

                if self.authenticate_external():
                    self.connected_usb_device = tokens[2]
                    print(f"VDGS [USB]: Mapping successful. Connected '{tokens[2]}' to /mnt/usb")
                return True

            elif len(tokens) > 1 and tokens[1] == "--disconnect":
                if not self.connected_usb_device:
                    print("VDGS [USB]: No active virtual USB device found.")
                    return True
                print(f"VDGS [USB]: Device '{self.connected_usb_device}' has been safely disconnected.")
                self.connected_usb_device = None
                return True
            else:
                print("Usage:\n  vdgs-usb --connect [Name] [Path]\n  vdgs-usb --disconnect")
                return True

        # --- Network Isolation Management Commands ---
        if cmd == "vdgs-net":
            if len(tokens) > 1 and tokens[1] == "--connect":
                if self.is_network_enabled:
                    print("VDGS [Network]: Network interface is already active.")
                    return True
                if self.authenticate_external():
                    self.is_network_enabled = True
                    print("VDGS [Network]: 🌐 Network interface enabled (Isolation Lifted).")
                return True

            elif len(tokens) > 1 and tokens[1] == "--disconnect":
                if not self.is_network_enabled:
                    print("VDGS [Network]: Network is already isolated.")
                    return True
                self.is_network_enabled = False
                print("VDGS [Network]: 🔒 Network connection terminated (Isolated).")
                return True
            else:
                print("Usage:\n  vdgs-net --connect\n  vdgs-net --disconnect")
                return True

        return False

    def verify_linux_executable(self, file_path):
        """Verifies if the target is a strict Linux binary (ELF) or UNIX script."""
        # 1. Block Windows/macOS malicious binary extensions
        forbidden_exts = ['.exe', '.app', '.bat', '.cmd', '.msi', '.lnk']
        _, ext = os.path.splitext(file_path.lower())
        if ext in forbidden_exts:
            print(f"VDGS [Error]: Execution denied. Format '{ext}' is incompatible with native Linux systems.")
            return False

        # 2. Strict inspection of binary magic numbers
        try:
            with open(file_path, "rb") as f:
                header = f.read(4)
                
                # Native Linux Standard Binary (ELF Format: 0x7F 'E' 'L' 'F')
                if header == b'\x7fELF':
                    return True
                
                # UNIX-compatible Shebang text scripts
                if header.startswith(b'#!'):
                    f.seek(0)
                    content = f.read().decode('utf-8', errors='ignore')
                    # Static scan for sandbox escape parameters inside the code
                    if "../" in content or "/etc" in content or "/var" in content:
                        print("VDGS [Security Alert]: Execution blocked. Malicious out-of-bounds access detected inside the script code.")
                        return False
                    return True
            print("VDGS [Error]: Execution denied. Only Native Linux ELF binaries or UNIX scripts are supported.")
            return False
        except Exception as e:
            print(f"VDGS [Error]: Binary verification failed due to an exception. ({e})")
            return False

    def open_interactive_window(self):
        """Spawns an isolated native Bash shell terminal instance in a separate window."""
        print("[VDGS System] 🖥️ Initializing external user terminal instance...")
        
        proxy_env = ""
        if not self.is_network_enabled:
            if self.os_type == "Windows":
                proxy_env = "set http_proxy=http://127.0.0.1:9999_blocked_by_vdgs && set https_proxy=http://127.0.0.1:9999_blocked_by_vdgs && "
            else:
                proxy_env = "export http_proxy=http://127.0.0.1:9999_blocked_by_vdgs && export https_proxy=http://127.0.0.1:9999_blocked_by_vdgs && "

        try:
            if self.os_type == "Windows":
                cmd_string = f'start cmd /k "title VDGS Interactive Terminal && {proxy_env} cd /d {self.host_current_path} && bash -i"'
                subprocess.Popen(cmd_string, shell=True)

            elif self.os_type == "Darwin":
                escaped_path = self.host_current_path.replace('"', '\\"')
                script = f'tell application "Terminal" to do script "{proxy_env} cd \\"{escaped_path}\\" && /bin/bash -i"'
                subprocess.Popen(["osascript", "-e", script])

            else:
                terminals = ["gnome-terminal", "xfce4-terminal", "xterm", "x-terminal-emulator"]
                launched = False
                for term in terminals:
                    try:
                        if term == "gnome-terminal":
                            subprocess.Popen([term, "--", "/bin/bash", "-c", f"{proxy_env} cd '{self.host_current_path}' && /bin/bash -i"])
                        else:
                            subprocess.Popen([term, "-e", f"/bin/bash -c \"{proxy_env} cd '{self.host_current_path}' && /bin/bash -i\""])
                        launched = True
                        break
                    except FileNotFoundError:
                        continue
                if not launched:
                    print("VDGS [System Error]: No compatible X11 terminal emulator (e.g., gnome-terminal) discovered.")

            print("[VDGS System] 🔓 Terminal window attached successfully. Close the external window when done or manage states below.")

        except Exception as e:
            print(f"VDGS [System Error]: Window generation failed: {e}")

    def boot(self):
        print("==================================================================")
        print("    Virtual Linux Directory Generation System (VDGS) v5.0         ")
        print("==================================================================")
        print(f"[VDGS Root] {self.host_root_path}")
        print(f"[Host OS  ] {self.os_type}")
        print(f"[HW Status] 💾 USB: Disconnected | 🌐 Network: 🔒 Isolated (OFF)")
        print("[Commands ] Type 'vdgs-usb' or 'vdgs-net' for authentication control.")
        print("[Terminal ] Type 'open' to deploy an isolated external Bash window.")
        print("==================================================================\n")

        while self.is_running:
            try:
                cmd_input = input(f"VDGS-Controller# ").strip()
                if not cmd_input:
                    continue
                
                if cmd_input == "exit":
                    print("\n[VDGS] Shutting down system securely.")
                    self.is_running = False
                    break
                
                if cmd_input == "open":
                    self.open_interactive_window()
                    continue

                tokens = cmd_input.split()
                if self.handle_vdgs_commands(tokens):
                    continue
                
                if not self.pre_check_security(cmd_input):
                    print("VDGS [Security Alert]: Out-of-bounds access blocked.")
                    continue
                
                if self.os_type == "Windows":
                    subprocess.run(["bash", "-c", cmd_input], cwd=self.host_current_path)
                else:
                    subprocess.run(["/bin/bash", "-c", cmd_input], cwd=self.host_current_path)

            except KeyboardInterrupt:
                print("\nType 'exit' to shutdown system securely.")

if __name__ == "__main__":
    vdgs_system = VDGS("virtual_root")
    vdgs_system.boot()
